version: '3.3'
services:
  # db:
  #   image: postgres:13.0-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   env_file:
  #     - ./.env
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     timeout: 10s
  #     interval: 1s
  #     retries: 10
  frontend:
    # image: vasilekx/foodgram_frontend:latest
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
      # - frontend_data:/app/result_build/  # don't work
  nginx:
    image: nginx:1.19.3
    network_mode: "host"  # для работы с локальныим проектом
    ports:
      - "80:80"
    volumes:
      # - static_value:/var/html/static/
      # - media_value:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      # - frontend_data:/usr/share/nginx/html/  # don't work
      - ../docs/:/usr/share/nginx/html/api/docs/

# volumes:
#   frontend_data:
#   postgres_data:
#  static_value:
#  media_value:
