# Generated by Django 2.2.16 on 2022-06-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_auto_20220624_1144'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_relationships',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_relationships',
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_relationships',
        ),
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='unique_relationships',
        ),
        migrations.RemoveConstraint(
            model_name='recipetag',
            name='unique_relationships',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_relationships',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='Favorite_unique_relationships'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='Follow_unique_relationships'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='Ingredient_unique_relationships'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='RecipeIngredient_unique_relationships'),
        ),
        migrations.AddConstraint(
            model_name='recipetag',
            constraint=models.UniqueConstraint(fields=('recipe', 'tag'), name='RecipeTag_unique_relationships'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='ShoppingCart_unique_relationships'),
        ),
    ]
