# Generated by Django 2.2.16 on 2022-06-07 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_auto_20220606_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(through='foodgram.RecipeTag', to='foodgram.Tag'),
        ),
        migrations.AlterField(
            model_name='recipetag',
            name='recipe',
            field=models.ForeignKey(help_text='Рецепт, к которому будет относиться тег', null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodgram.Recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipetag',
            name='tags',
            field=models.ForeignKey(help_text='Тег, к которому будет относиться рецепт', null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodgram.Tag', verbose_name='Тег'),
        ),
    ]
