# Generated by Django 2.2.16 on 2022-06-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_auto_20220607_1422'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipetag',
            name='unique_relationships',
        ),
        migrations.RenameField(
            model_name='recipetag',
            old_name='tags',
            new_name='tag',
        ),
        migrations.AddConstraint(
            model_name='recipetag',
            constraint=models.UniqueConstraint(fields=('recipe', 'tag'), name='unique_relationships'),
        ),
    ]
