# Generated by Django 2.2.16 on 2022-06-09 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0005_auto_20220608_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetag',
            name='tag',
            field=models.ForeignKey(help_text='Тег, к которому будет относиться рецепт', null=True, on_delete=django.db.models.deletion.CASCADE, to='foodgram.Tag', verbose_name='Тег'),
        ),
    ]
