# Generated by Django 2.2.16 on 2022-06-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0007_auto_20220609_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-id'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
