# Generated by Django 2.2.16 on 2022-06-16 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0010_auto_20220615_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(help_text='Рецепт, который есть у пользователей как любимый рецепт', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='foodgram.Recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ForeignKey(help_text='Рецепт, который есть у пользователей в списке покупок', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='foodgram.Recipe', verbose_name='Рецепт'),
        ),
    ]
