# Generated by Django 2.2.16 on 2022-06-17 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0014_auto_20220617_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
