# Generated by Django 2.2.16 on 2022-06-18 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0015_auto_20220617_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(help_text='Ингредиент, к которому будет относиться рецепт', null=True, on_delete=django.db.models.deletion.CASCADE, to='foodgram.Ingredient', verbose_name='Ингредиент'),
        ),
    ]
